name: meta_weather_api
description: A Dart  API Client for the MetaWeather API.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.4.0
  http: ^0.13.4
  

dev_dependencies:
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  test: ^1.19.5
  mocktail: ^0.2.0

