name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  meta_weather_api:
    path: ../meta_weather_api

dev_dependencies:
  json_serializable: ^6.1.1
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  test: ^1.19.5
  mocktail: ^0.2.0